# Generated by Django 4.1.2 on 2022-11-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "cartId",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("userId", models.CharField(max_length=20)),
                ("userName", models.CharField(max_length=15, unique=True)),
                ("wareId", models.CharField(max_length=20)),
                (
                    "wareCount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("createTime", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "orderId",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("userId", models.CharField(max_length=20)),
                ("userName", models.CharField(max_length=15, unique=True)),
                ("wareId", models.CharField(max_length=20)),
                (
                    "wareCount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("createTime", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "salesId",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("yearName", models.CharField(max_length=5)),
                (
                    "yearSales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("yearEvents", models.CharField(default="", max_length=30)),
                ("monthSales", models.JSONField(null=True)),
                ("wareSales", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userId",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("userName", models.CharField(max_length=15, unique=True)),
                ("userPassword", models.CharField(max_length=20)),
                (
                    "userPower",
                    models.DecimalField(decimal_places=0, default=0, max_digits=3),
                ),
                ("createTime", models.DateTimeField(null=True)),
                ("updateTime", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ware",
            fields=[
                (
                    "wareId",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("wareName", models.CharField(max_length=15, unique=True)),
                (
                    "warePower",
                    models.DecimalField(decimal_places=0, default=0, max_digits=3),
                ),
                (
                    "wareCount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("createTime", models.DateTimeField(null=True)),
                ("updateTime", models.DateTimeField(null=True)),
            ],
        ),
    ]
